#!/usr/bin/env python3
"""
Script to create the Visual Hierarchy Excel workbook with dimReasonCodes data
"""

import openpyxl
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.worksheet.page import PageMargins

# Define the complete dataset
data = [
    ["Downtime Category", "Sub Category", "Root Cause"],
    ["Machine Issue", "Belling Machine", "Mandrel Fault"],
    ["Machine Issue", "Belling Machine", "Cylinder Failure"],
    ["Machine Issue", "Belling Machine", "Transfers"],
    ["Machine Issue", "Belling Machine", "Drive Issue"],
    ["Machine Issue", "Belling Machine", "Encoder Fault"],
    ["Machine Issue", "Belling Machine", "Seal Fault"],
    ["Machine Issue", "Belling Machine", "Oven Failure"],
    ["Machine Issue", "Belling Machine", "Travel Issue"],
    ["Machine Issue", "Belling Machine", "Hydraulic Fault"],
    ["Machine Issue", "Belling Machine", "Clamps Issue"],
    ["Machine Issue", "Belling Machine", "Pump Fault"],
    ["Machine Issue", "Belling Machine", "Pusher Fault"],
    ["Machine Issue", "Belling Machine", "Sensor Fault"],
    ["Machine Issue", "Belling Machine", "Belling Speed"],
    ["Machine Issue", "Belling Machine", "Ring Loader"],
    ["Machine Issue", "Belling Machine", "Jam Up"],
    ["Machine Issue", "Belling Machine", "Roller Failure"],
    ["Machine Issue", "Belling Machine", "Air Fault"],
    ["Machine Issue", "Belling Machine", "Electrical Fault"],
    ["Machine Issue", "Belling Machine", "Belling Tool"],
    ["Machine Issue", "Belling Machine", "Keyway Issue"],
    ["Machine Issue", "Belling Machine", "Setup Error"],
    ["Machine Issue", "Belling Machine", "Belt Failure"],
    ["Machine Issue", "Belling Machine", "Water Issue"],
    ["Machine Issue", "Belling Machine", "Machine Others"],
    ["Machine Issue", "Saw", "Failed to Cut"],
    ["Machine Issue", "Saw", "Spring Issue"],
    ["Machine Issue", "Saw", "Saw Issues"],
    ["Machine Issue", "Saw", "Blade Dull/Blunt"],
    ["Machine Issue", "Saw", "Blade Breakage"],
    ["Machine Issue", "Saw", "Swarf Build Up"],
    ["Machine Issue", "Saw", "Blade Alignment"],
    ["Machine Issue", "Saw", "Motor Failure"],
    ["Machine Issue", "Saw", "Electrical Fault"],
    ["Machine Issue", "Saw", "Air Fault"],
    ["Machine Issue", "Saw", "Hydraulic Fault"],
    ["Machine Issue", "Saw", "Sensor Fault"],
    ["Machine Issue", "Saw", "Jam Up"],
    ["Machine Issue", "Saw", "Rotor Issue"],
    ["Machine Issue", "Saw", "Clamp Failure"],
    ["Machine Issue", "Saw", "Guard/Safety Interlock"],
    ["Machine Issue", "Saw", "Setup Error"],
    ["Machine Issue", "Saw", "Machine Others"],
    ["Machine Issue", "Crane", "Machine Others"],
    ["Machine Issue", "Crane", "Crane Out of Service"],
    ["Machine Issue", "Stacker", "Jam / Blockage"],
    ["Machine Issue", "Stacker", "Motor Failure"],
    ["Machine Issue", "Stacker", "Arms Failure"],
    ["Machine Issue", "Stacker", "Oil Issue"],
    ["Machine Issue", "Stacker", "Light Curtain"],
    ["Machine Issue", "Stacker", "Gearbox/Drive Fault"],
    ["Machine Issue", "Stacker", "Rotator Fault"],
    ["Machine Issue", "Stacker", "Lost Memory"],
    ["Machine Issue", "Stacker", "Electrical Fault"],
    ["Machine Issue", "Stacker", "Sensor Fault"],
    ["Machine Issue", "Stacker", "Air Fault"],
    ["Machine Issue", "Stacker", "Alignment Issue"],
    ["Machine Issue", "Stacker", "Bearing Failure"],
    ["Machine Issue", "Stacker", "Roller/Conveyor Failure"],
    ["Machine Issue", "Stacker", "Mechanical Fault"],
    ["Machine Issue", "Stacker", "Guard/Safety Interlock"],
    ["Machine Issue", "Stacker", "Setup Error"],
    ["Machine Issue", "Stacker", "Machine Others"],
    ["Machine Issue", "Extruder", "Heat Elements"],
    ["Machine Issue", "Extruder", "Screw and Barrel"],
    ["Machine Issue", "Extruder", "Controls Issues"],
    ["Machine Issue", "Extruder", "Temperature Control"],
    ["Machine Issue", "Extruder", "Electrical Fault"],
    ["Machine Issue", "Extruder", "Hydraulic Fault"],
    ["Machine Issue", "Extruder", "Mechanical Fault"],
    ["Machine Issue", "Extruder", "Tooling Issue"],
    ["Machine Issue", "Extruder", "Set-up Error"],
    ["Machine Issue", "Extruder", "Material Feed Issue"],
    ["Machine Issue", "Extruder", "Vacuum Fault"],
    ["Machine Issue", "Extruder", "Sensor Fault"],
    ["Machine Issue", "Extruder", "Overload/Trip"],
    ["Machine Issue", "Extruder", "Strip and Clean"],
    ["Machine Issue", "Extruder", "Machine Others"],
    ["Machine Issue", "CoExtruder", "Drive Failure"],
    ["Machine Issue", "CoExtruder", "Heat Elements"],
    ["Machine Issue", "CoExtruder", "Screw/Auger Failure"],
    ["Machine Issue", "CoExtruder", "Barrel Issues"],
    ["Machine Issue", "CoExtruder", "PLC/Control Fault"],
    ["Machine Issue", "CoExtruder", "Temperature Control"],
    ["Machine Issue", "CoExtruder", "Electrical Fault"],
    ["Machine Issue", "CoExtruder", "Hydraulic Fault"],
    ["Machine Issue", "CoExtruder", "Mechanical Fault"],
    ["Machine Issue", "CoExtruder", "Tooling Issue"],
    ["Machine Issue", "CoExtruder", "Set-up Error"],
    ["Machine Issue", "CoExtruder", "Material Feed Issue"],
    ["Machine Issue", "CoExtruder", "Sensor Fault"],
    ["Machine Issue", "CoExtruder", "Overload/Trip"],
    ["Machine Issue", "CoExtruder", "Machine Others"],
    ["Machine Issue", "Haul Off", "Chain Failure"],
    ["Machine Issue", "Haul Off", "Motor Failure"],
    ["Machine Issue", "Haul Off", "Gearbox/Drive Fault"],
    ["Machine Issue", "Haul Off", "Synchro Fault"],
    ["Machine Issue", "Haul Off", "Electrical Fault"],
    ["Machine Issue", "Haul Off", "Sensor Fault"],
    ["Machine Issue", "Haul Off", "Jam Up"],
    ["Machine Issue", "Haul Off", "Roller Failure"],
    ["Machine Issue", "Haul Off", "Belt Failure"],
    ["Machine Issue", "Haul Off", "Air Fault"],
    ["Machine Issue", "Haul Off", "Hydraulic Fault"],
    ["Machine Issue", "Haul Off", "Pipe Slipping "],
    ["Machine Issue", "Haul Off", "Guard/Safety Interlock"],
    ["Machine Issue", "Haul Off", "Alignment Issue"],
    ["Machine Issue", "Haul Off", "Setup Error"],
    ["Machine Issue", "Haul Off", "Mechanical Fault"],
    ["Machine Issue", "Haul Off", "Keyway Issue"],
    ["Machine Issue", "Haul Off", "Machine Others"],
    ["Machine Issue", "Conveyor", "Belt Failure"],
    ["Machine Issue", "Conveyor", "Motor Failure"],
    ["Machine Issue", "Conveyor", "Gearbox/Drive Fault"],
    ["Machine Issue", "Conveyor", "Electrical Fault"],
    ["Machine Issue", "Conveyor", "Sensor Fault"],
    ["Machine Issue", "Conveyor", "Jam / Blockage"],
    ["Machine Issue", "Conveyor", "Roller Failure"],
    ["Machine Issue", "Conveyor", "Alignment Issue"],
    ["Machine Issue", "Conveyor", "Guard/Safety Interlock"],
    ["Machine Issue", "Conveyor", "Air Fault"],
    ["Machine Issue", "Conveyor", "Setup Error"],
    ["Machine Issue", "Conveyor", "Mechanical Fault"],
    ["Machine Issue", "Conveyor", "Machine Others"],
    ["Machine Issue", "Strapper", "Jam / Blockage"],
    ["Machine Issue", "Strapper", "Motor Failure"],
    ["Machine Issue", "Strapper", "Gearbox/Drive Fault"],
    ["Machine Issue", "Strapper", "Electrical Fault"],
    ["Machine Issue", "Strapper", "Sensor Fault"],
    ["Machine Issue", "Strapper", "Air Fault"],
    ["Machine Issue", "Strapper", "Alignment Issue"],
    ["Machine Issue", "Strapper", "Roller/Conveyor Failure"],
    ["Machine Issue", "Strapper", "Mechanical Fault"],
    ["Machine Issue", "Strapper", "Guard/Safety Interlock"],
    ["Machine Issue", "Strapper", "Setup Error"],
    ["Machine Issue", "Strapper", "Machine Others"],
    ["Machine Issue", "Ring Loader", "Ring Loader Issue"],
    ["Machine Issue", "Rollepaal", "Screen Failure"],
    ["Machine Issue", "Rollepaal", "Controls Failure"],
    ["Machine Issue", "Rollepaal", "Machine Others"],
    ["Machine Issue", "Heat Exchanger", "Heat Exchanger"],
    ["Machine Issue", "Impact Tower", "Cable Snapped"],
    ["Machine Issue", "Impact Tower", "Impact Tower Issues"],
    ["Machine Issue", "Light Curtain", "Out of Allignment"],
    ["Machine Issue", "Light Curtain", "Machine Others"],
    ["Machine Issue", "Vacuum Tank", "Vacuum Leak"],
    ["Machine Issue", "Vacuum Tank", "Sleeve Issue"],
    ["Machine Issue", "Vacuum Tank", "Hose Failure"],
    ["Machine Issue", "Vacuum Tank", "Tank Travel Fault"],
    ["Machine Issue", "Vacuum Tank", "Pump Failure"],
    ["Machine Issue", "Vacuum Tank", "Water Issue"],
    ["Machine Issue", "Vacuum Tank", "Sensor Fault"],
    ["Machine Issue", "Vacuum Tank", "Electrical Fault"],
    ["Machine Issue", "Vacuum Tank", "Mechanical Fault"],
    ["Machine Issue", "Vacuum Tank", "Blockage"],
    ["Machine Issue", "Vacuum Tank", "Setup Error"],
    ["Machine Issue", "Vacuum Tank", "Valve Failure"],
    ["Machine Issue", "Vacuum Tank", "Temperature Issue"],
    ["Machine Issue", "Vacuum Tank", "Machine Others"],
    ["Machine Issue", "Spray Tank", "Water Leak"],
    ["Machine Issue", "Spray Tank", "Sleeve Issue"],
    ["Machine Issue", "Spray Tank", "Hose Failure"],
    ["Machine Issue", "Spray Tank", "Tank Travel Fault"],
    ["Machine Issue", "Spray Tank", "Pump Failure"],
    ["Machine Issue", "Spray Tank", "Water Issue"],
    ["Machine Issue", "Spray Tank", "Sensor Fault"],
    ["Machine Issue", "Spray Tank", "Electrical Fault"],
    ["Machine Issue", "Spray Tank", "Mechanical Fault"],
    ["Machine Issue", "Spray Tank", "Blockage"],
    ["Machine Issue", "Spray Tank", "Setup Error"],
    ["Machine Issue", "Spray Tank", "Valve Failure"],
    ["Machine Issue", "Spray Tank", "Temperature Issue"],
    ["Machine Issue", "Spray Tank", "Machine Others"],
    ["Machine Issue", "Barrel Vac", "No Vacuum"],
    ["Machine Issue", "Barrel Vac", "Pump Tripped Out"],
    ["Machine Issue", "Barrel Vac", "No Vacuum Available"],
    ["Machine Issue", "Barrel Vac", "Blocked"],
    ["Machine Issue", "Barrel Vac", "Not Cleaned"],
    ["Machine Issue", "Barrel Vac", "Damaged Hose"],
    ["Machine Issue", "Barrel Vac", "Machine Others"],
    ["Machine Issue", "Compressor", "Compressor Failure"],
    ["Machine Issue", "Compressor", "Machine Others"],
    ["Machine Issue", "Mixing Plant", "Feeder Blockage"],
    ["Machine Issue", "Mixing Plant", "Mixer Down"],
    ["Machine Issue", "Mixing Plant", "Weighing System Error"],
    ["Machine Issue", "Mixing Plant", "Material Segregation"],
    ["Machine Issue", "Mixing Plant", "Silo/Storage Issue"],
    ["Machine Issue", "Mixing Plant", "Setup/Error"],
    ["Machine Issue", "Mixing Plant", "Sensor Fault"],
    ["Machine Issue", "Mixing Plant", "Contamination"],
    ["Machine Issue", "Mixing Plant", "Machine Others"],
    ["Machine Issue", "Chiller", "Chiller Down"],
    ["Machine Issue", "Chiller", "Leak"],
    ["Machine Issue", "Chiller", "Pump Failure"],
    ["Machine Issue", "Chiller", "Electrical Fault"],
    ["Machine Issue", "Chiller", "Sensor Fault"],
    ["Machine Issue", "Chiller", "Control System Fault"],
    ["Machine Issue", "Chiller", "Water Issue"],
    ["Machine Issue", "Chiller", "Heat Exchanger Blockage"],
    ["Machine Issue", "Chiller", "Temperature Issue"],
    ["Machine Issue", "Chiller", "Setup/Error"],
    ["Machine Issue", "Chiller", "Guard/Safety Interlock"],
    ["Machine Issue", "Chiller", "Machine Others"],
    ["Machine Issue", "Slotter", "Machine Others"],
    ["Machine Issue", "Strapper", "Strapper Issues"],
    ["Machine Issue", "Busch Pump", "Tripped Out"],
    ["Machine Issue", "Busch Pump", "Blocked"],
    ["Machine Issue", "Busch Pump", "Machine Others"],
    ["Machine Issue", "Impact Tower", "Snapped Cable"],
    ["Machine Issue", "Impact Tower", "Breakdown"],
    ["Machine Issue", "Impact Tower", "Impact Tower Issues"],
    ["Machine Issue", "Corrigator", "Electrical Fault"],
    ["Machine Issue", "Corrigator", "PLC Control"],
    ["Machine Issue", "Corrigator", "Drive Issue"],
    ["Machine Issue", "Corrigator", "Bearing Failure"],
    ["Machine Issue", "Corrigator", "Air Fault"],
    ["Machine Issue", "Corrigator", "Mechanical Failure"],
    ["Machine Issue", "Corrigator", "Human Error"],
    ["Machine Issue", "Corrigator", "Machine Others"],
    ["Machine Issue", "Machine Others", "Machine Others"],
    ["Material Issue", "No Mix", "No Raw Metrials or Resin"],
    ["Material Issue", "No Mix", "Run Out of Mix"],
    ["Material Issue", "No Mix", "Not Mixed"],
    ["Material Issue", "No Mix", "Wrong Mix Made"],
    ["Material Issue", "No Mix", "Demand Change"],
    ["Material Issue", "No Mix", "Material Others"],
    ["Material Issue", "No Stock", "Timbers"],
    ["Material Issue", "No Stock", "Scallops"],
    ["Material Issue", "No Stock", "Rings"],
    ["Material Issue", "No Stock", "Stickers"],
    ["Material Issue", "No Stock", "Printer"],
    ["Material Issue", "No Stock", "Bundle Strap"],
    ["Material Issue", "No Stock", "Hand Strapper"],
    ["Material Issue", "No Stock", "Nails"],
    ["Material Issue", "No Stock", "Plastic"],
    ["Material Issue", "No Stock", "Demand Change"],
    ["Material Issue", "No Stock", "Material Others"],
    ["Material Issue", "Contamination", "Rubber"],
    ["Material Issue", "Contamination", "Foreign Material"],
    ["Material Issue", "Contamination", "B/Vac residue"],
    ["Material Issue", "Contamination", "Color"],
    ["Material Issue", "Contamination", "Mix Cross-Contamination"],
    ["Material Issue", "Contamination", "Silo Washout"],
    ["Material Issue", "Contamination", "Overprocessed Material"],
    ["Material Issue", "Contamination", "Supplier Contamination"],
    ["Material Issue", "Contamination", "Material Others"],
    ["Material Issue", "Material Feed", "Feeder Blockage"],
    ["Material Issue", "Material Feed", "Damaged Hoses"],
    ["Material Issue", "Material Feed", "Feeder Calibration Error"],
    ["Material Issue", "Material Feed", "Material Bridging"],
    ["Material Issue", "Material Feed", "Hopper Empty"],
    ["Material Issue", "Material Feed", "Conveying System Fault"],
    ["Material Issue", "Material Feed", "Sensor Fault"],
    ["Material Issue", "Material Feed", "Material Pump Fault"],
    ["Material Issue", "Material Feed", "Setup/Error"],
    ["Material Issue", "Material Feed", "Material Others"],
    ["Material Issue", "Torque Unstable", "Torque Unstable"],
    ["Material Issue", "Bad Mix", "Bad Mix"],
    ["Material Issue", "Bad Mix", "Material Others"],
    ["Material Issue", "Bridging", "Material Bridging"],
    ["Material Issue", "Foaming Issues", "Under/Over Foaming"],
    ["Material Issue", "Foaming Issues", "Not Foaming"],
    ["Material Issue", "Foaming Issues", "Material Others"],
    ["Material Issue", "Material Others", "Material Others"],
    ["Quality Issue", "Sockets", "Bad Socket Profile"],
    ["Quality Issue", "Sockets", "Clamp Marks"],
    ["Quality Issue", "Sockets", "Short Sockets"],
    ["Quality Issue", "Sockets", "Ring Issues"],
    ["Quality Issue", "Sockets", "Ripples"],
    ["Quality Issue", "Sockets", "Tight Sockets"],
    ["Quality Issue", "Sockets", "Roller/Feed Issue"],
    ["Quality Issue", "Sockets", "Setup Error"],
    ["Quality Issue", "Sockets", "Cooling Issue"],
    ["Quality Issue", "Sockets", "Human Error"],
    ["Quality Issue", "Sockets", "Quality Others"],
    ["Quality Issue", "Wall Thickness", "Wall Too Thick"],
    ["Quality Issue", "Wall Thickness", "Wall Too Thin"],
    ["Quality Issue", "Wall Thickness", "Wall Inconsistent"],
    ["Quality Issue", "Wall Thickness", "Startup Variation"],
    ["Quality Issue", "Wall Thickness", "Bad Pipe Centre"],
    ["Quality Issue", "Wall Thickness", "Human Error"],
    ["Quality Issue", "Wall Thickness", "Quality Others"],
    ["Quality Issue", "Rougness", "Lost Vacuum"],
    ["Quality Issue", "Rougness", "Quality Others"],
    ["Quality Issue", "Pin Holes", "Quality Others"],
    ["Quality Issue", "Pin Holes", "Pin Holes"],
    ["Quality Issue", "Pipe Finish", "Roughness"],
    ["Quality Issue", "Pipe Finish", "Discoloration"],
    ["Quality Issue", "Pipe Finish", "Blisters"],
    ["Quality Issue", "Pipe Finish", "Water Marks"],
    ["Quality Issue", "Pipe Finish", "Rings"],
    ["Quality Issue", "Pipe Finish", "Scratches/Scuffing"],
    ["Quality Issue", "Wine Glass", "Wine Glass"],
    ["Quality Issue", "Wine Glass", "Quality Others"],
    ["Quality Issue", "Pipe Finish", "Processing Too Hot"],
    ["Quality Issue", "Pipe Finish", "Human Error"],
    ["Quality Issue", "Pipe Finish", "Setup Error"],
    ["Quality Issue", "Pipe Finish", "Quality Others"],
    ["Quality Issue", "Weights", "Running Heavy"],
    ["Quality Issue", "Weights", "Quality Others"],
    ["Quality Issue", "OD ID", "OD/ID Out of Spec"],
    ["Quality Issue", "OD ID", "Sleeve Issue"],
    ["Quality Issue", "OD ID", "Material Variation"],
    ["Quality Issue", "OD ID", "Unclear Quality Standards"],
    ["Quality Issue", "OD ID", "Sensor Fault"],
    ["Quality Issue", "OD ID", "Startup Variation"],
    ["Quality Issue", "OD ID", "Human Error"],
    ["Quality Issue", "OD ID", "Quality Others"],
    ["Quality Issue", "Ovality", "Out of Spec Ovality"],
    ["Quality Issue", "Ovality", "Cooling Tank Issues"],
    ["Quality Issue", "Ovality", "Vacuum Tank Water"],
    ["Quality Issue", "Ovality", "OCD"],
    ["Quality Issue", "Ovality", "Material Ovality Issues"],
    ["Quality Issue", "Ovality", "Startup Variation"],
    ["Quality Issue", "Ovality", "Human Error"],
    ["Quality Issue", "Ovality", "Setup Error"],
    ["Quality Issue", "Ovality", "Quality Others"],
    ["Quality Issue", "Screw Marks", "Screw Marks"],
    ["Quality Issue", "Screw Marks", "Quality Others"],
    ["Quality Issue", "Water Marks", "Water Marks"],
    ["Quality Issue", "Water Marks", "Blocked Sprayers"],
    ["Quality Issue", "Water Marks", "Water Level"],
    ["Quality Issue", "Water Marks", "Quality Others"],
    ["Quality Issue", "Grooves or Score Marks", "Groove/Score From Head"],
    ["Quality Issue", "Grooves or Score Marks", "Groove/Score From Pin"],
    ["Quality Issue", "Grooves or Score Marks", "Tooling Wear/Damage"],
    ["Quality Issue", "Grooves or Score Marks", "Groove/Score Vacuum Tank"],
    ["Quality Issue", "Grooves or Score Marks", "Groove/Score from Sleeve"],
    ["Quality Issue", "Grooves or Score Marks", "Startup Variation"],
    ["Quality Issue", "Grooves or Score Marks", "Human Error"],
    ["Quality Issue", "Grooves or Score Marks", "Quality Others"],
    ["Quality Issue", "Impact", "Wall Thickness"],
    ["Quality Issue", "Impact", "Material Degradation"],
    ["Quality Issue", "Impact", "Poor Gelation"],
    ["Quality Issue", "Impact", "Melt Too High/Low"],
    ["Quality Issue", "Impact", "Cooling Issue"],
    ["Quality Issue", "Impact", "Tooling Wear/Damage"],
    ["Quality Issue", "Impact", "Startup Variation"],
    ["Quality Issue", "Impact", "Human Error"],
    ["Quality Issue", "Impact", "Sensor Fault"],
    ["Quality Issue", "Impact", "Testing Equipment Unavailable"],
    ["Quality Issue", "Impact", "Impact Failure"],
    ["Quality Issue", "Impact", "Quality Others"],
    ["Quality Issue", "Pressure", "Pressure Failure"],
    ["Quality Issue", "Pressure", "Quality Others"],
    ["Quality Issue", "Length", "Too Long"],
    ["Quality Issue", "Length", "Too Short"],
    ["Quality Issue", "Length", "Inconsistent Length"],
    ["Quality Issue", "Length", "Saw Setting Error"],
    ["Quality Issue", "Length", "Sensor Fault"],
    ["Quality Issue", "Length", "Startup Variation"],
    ["Quality Issue", "Length", "Human Error"],
    ["Quality Issue", "Length", "Setup Error"],
    ["Quality Issue", "Length", "Quality Others"],
    ["Quality Issue", "Print Message", "Incorrect Print"],
    ["Quality Issue", "Print Message", "No Print"],
    ["Quality Issue", "Print Message", "No Available Printer"],
    ["Quality Issue", "Print Message", "Quality Others"],
    ["Quality Issue", "Stiffness", "Stiffness Out of Spec"],
    ["Quality Issue", "Stiffness", "Material Stiffness Issues"],
    ["Quality Issue", "Stiffness", "Testing Equipment Unavailable"],
    ["Quality Issue", "Stiffness", "Skin Distribution Stiffness Issues"],
    ["Quality Issue", "Stiffness", "Processing Stiffness Issues"],
    ["Quality Issue", "Stiffness", "Human Error"],
    ["Quality Issue", "Stiffness", "Quality Others"],
    ["Quality Issue", "Blisters", "Blisters"],
    ["Quality Issue", "Pin Holes", "Quality Others"],
    ["Quality Issue", "Quality Others", "Quality Others"],
    ["Rework", "Rebelling", "Slow Rebelling"],
    ["Rework", "Rebelling", "Rework Others"],
    ["Rework", "Delay due to Rework", "Delay Due to Rework"],
    ["Rework", "Delay due to Rework", "Rework Others"],
    ["Rework", "Rework Others", "Rework Others"],
    ["Labour Issues", "No Labour", "Absenteeism"],
    ["Labour Issues", "No Labour", "Sick Leave"],
    ["Labour Issues", "No Labour", "Annual Leave"],
    ["Labour Issues", "No Labour", "Went Home"],
    ["Labour Issues", "No Labour", "Workplace Incident"],
    ["Labour Issues", "No Labour", "EBA/Meeting"],
    ["Labour Issues", "Staff on Other Lines", "Staff on Other Lines"],
    ["Labour Issues", "Unavailable Skills", "Lack of Experienced Staff"],
    ["Labour Issues", "Unavailable Skills", "No Fitter"],
    ["Labour Issues", "Unavailable Skills", "No Electrician"],
    ["Labour Issues", "Workplace Incident", "Workplace Incident"],
    ["Line Running Slow", "Extruder Speed", "Burns Prevention"],
    ["Line Running Slow", "Extruder Speed", "Torque Fluctuating"],
    ["Line Running Slow", "Extruder Speed", "Barrel Vacuum Issue"],
    ["Line Running Slow", "Extruder Speed", "Melt Fluctuating"],
    ["Line Running Slow", "Material Feed Speed", "Material Availability"],
    ["Line Running Slow", "Material Feed Speed", "Hopper Issue"],
    ["Line Running Slow", "Material Feed Speed", "Material Feed Spped"],
    ["Line Running Slow", "Nesting", "Nesting"],
    ["Line Running Slow", "Belling Speed", "Oven Time"],
    ["Line Running Slow", "Belling Speed", "Stacker Time"],
    ["Line Running Slow", "Ovality Issues", "Quality Control"],
    ["Line Running Slow", "Stacker Speed", "Hand Stacking"],
    ["Line Running Slow", "Temperature Control", "Quality Control"],
    ["Line Running Slow", "Unknown Slow", "Unknown Slow"],
    ["Startup or Changeover", "Startup Variation", "Startup Variation"],
    ["Startup or Changeover", "Material Change", "Material Change"],
    ["Startup or Changeover", "Startup Variation", "Startup Others"],
    ["Startup or Changeover", "Startup Others", "Startup Others"],
    ["Planned Down", "Planned Down", "Planned Down"],
    ["Schedule Change", "Internal Schedule Change", "Internal Schedule Change"],
    ["Schedule Change", "Planning Schedule Change", "Planning Schedule Change"],
    ["Services Issue", "Water Services", "Chiller Failure"],
    ["Services Issue", "Water Services", "Chiller Filtration Failure"],
    ["Services Issue", "Water Services", "Water Services Other"],
    ["Services Issue", "Electrical Services", "Power Failure"],
    ["Services Issue", "Electrical Services", "Failed Circuit"],
    ["Services Issue", "Electrical Services", "Electrical Others"],
    ["Services Issue", "Services Others", "Services Others"],
    ["Others", "No Routing", "Unusual Product"],
    ["Others", "Others", "Others"],
    ["Burns", "Extruder", "Screw Cooling"],
    ["Burns", "Extruder", "Screw"],
    ["Burns", "Extruder", "Heat Elements"],
    ["Burns", "Extruder", "Conditions Unstable"],
    ["Burns", "Extruder", "Processing Settings"],
    ["Burns", "Extruder", "Purge Burns"],
    ["Burns", "Extruder", "Setup Issue"],
    ["Burns", "Extruder", "Worn Tooling"],
    ["Burns", "Extruder", "Unknown Burns"],
    ["Burns", "Belling Table", "Oven Timing"],
    ["Burns", "Belling Table", "Oven Temps too High"],
    ["Burns", "Belling Table", "Oven Sensor Fault"],
    ["Burns", "Belling Table", "Electrical Fault"],
    ["Burns", "Belling Table", "Unknown Burns"],
    ["Burns", "Material Issue", "Contamination"],
    ["Burns", "Material Issue", "Melt Temp Fluctuating"],
    ["Burns", "Material Issue", "Bad Mix"],
    ["Burns", "Material Issue", "Unknown Burns"],
]

def create_workbook():
    """Create the Excel workbook with dimReasonCodes and Visual_Hierarchy sheets"""

    # Create new workbook
    wb = openpyxl.Workbook()

    # Remove default sheet
    if 'Sheet' in wb.sheetnames:
        del wb['Sheet']

    # Create dimReasonCodes sheet
    ws_data = wb.create_sheet("dimReasonCodes", 0)

    # Add data to dimReasonCodes sheet
    for row_idx, row_data in enumerate(data, start=1):
        for col_idx, value in enumerate(row_data, start=1):
            cell = ws_data.cell(row=row_idx, column=col_idx, value=value)

            # Format header row
            if row_idx == 1:
                cell.font = Font(bold=True, size=11)
                cell.fill = PatternFill(start_color="366092", end_color="366092", fill_type="solid")
                cell.font = Font(bold=True, size=11, color="FFFFFF")
                cell.alignment = Alignment(horizontal="center", vertical="center")

    # Adjust column widths for dimReasonCodes
    ws_data.column_dimensions['A'].width = 25
    ws_data.column_dimensions['B'].width = 25
    ws_data.column_dimensions['C'].width = 30

    # Create Visual_Hierarchy sheet
    ws_visual = wb.create_sheet("Visual_Hierarchy", 1)

    # Add instruction text
    ws_visual['A1'] = "Visual Hierarchy - Downtime Codes"
    ws_visual['A1'].font = Font(bold=True, size=16)
    ws_visual['A3'] = "Click the 'Refresh Visual Hierarchy' button to generate the visual hierarchy from dimReasonCodes data."
    ws_visual['A3'].font = Font(size=11, italic=True)

    ws_visual['A5'] = "Instructions:"
    ws_visual['A5'].font = Font(bold=True, size=11)
    ws_visual['A6'] = "1. Open the VBA editor (Alt+F11)"
    ws_visual['A7'] = "2. Insert a new module (Insert > Module)"
    ws_visual['A8'] = "3. Paste the VBA code provided in the separate text file"
    ws_visual['A9'] = "4. Close the VBA editor"
    ws_visual['A10'] = "5. Insert a button on this sheet (Developer tab > Insert > Button)"
    ws_visual['A11'] = "6. Assign the 'RefreshVisualHierarchy' macro to the button"
    ws_visual['A12'] = "7. Click the button to generate the visual hierarchy"

    # Set page setup for A3
    ws_visual.page_setup.paperSize = ws_visual.PAPERSIZE_A3
    ws_visual.page_setup.orientation = ws_visual.ORIENTATION_LANDSCAPE
    ws_visual.page_margins = PageMargins(left=0.5, right=0.5, top=0.5, bottom=0.5)

    # Adjust column widths for Visual_Hierarchy
    for col in range(1, 13):
        ws_visual.column_dimensions[openpyxl.utils.get_column_letter(col)].width = 15

    # Save workbook
    wb.save("Downtime_Visual_Hierarchy.xlsx")
    print("Excel workbook created successfully: Downtime_Visual_Hierarchy.xlsx")

if __name__ == "__main__":
    create_workbook()
